### Generic Messages

sucessMessage: '&9%prefix%> &7%message%'

errorMessage: '&4%prefix%> &c%message%'

infoMessage: '&6%prefix%> &b%message%'

permissionMessage: '&4Permission> &cYou do not have permission to do this! (%permission%)'

mustBePlayer: 'You must be a player to execute this command.'

### Commands

## GameMode

prefixGameMode: 'GameMode'

incorrectUsageGameMode: 'Incorrect Usage! Use /gamemode <mode> [player]'

invalidGameMode: 'The specified gamemode is invalid.'

targetNotOnlineGameMode: 'The target is not online.'

targetChangedGamemode: 'The gamemode of &e%target% &7was changed.'

targetChangedGamemode2: 'Your gamemode was changed by &6%player%'

## Heal

prefixHeal: 'Heal'

incorrectUsageHeal: 'Incorrect Usage! Use /heal [player]'

sucessHeal: 'You were healed.'

targetNotOnlineHeal: 'The target is not online.'

targetHeal: '&e%target% &7was healed.'

targetHeal2: 'You were healed by &e%player%&7.'

##Feed

prefixFeed: 'Feed'

incorrectUsageFeed: 'Incorrect Usage! Use /feed [player]'

sucessFeed: 'You were feed.'

targetNotOnlineFeed: 'The target is not online.'

targetFeed: '&e%target% &7was feed.'

targetFeed2: 'You were feed by &e%player%&7.'

## TpHere

prefixTpHere: 'Tphere'

incorrectUsageTpHere: 'Incorrect Usage! Use /tphere <player>'

targetNotOnlineTpHere: 'The target is not online.'

targetTpHere: '&e%target% &7was teleported to your location.'

targetTpHere2: 'You were teleported by %player%&b.'

## TpAll

prefixTpAll: 'Tpall'

sucessTpAll: 'All players were teleported to you!'

sucessTpAll2: 'You were teleported by %player%"&b.'

## ClearChat

prefixClearChat: 'ClearChat'

sucessClearChat: 'The chat was cleared sucessfully.'

sucessClearChat2: 'The chat was cleared by a moderator.'

## Clock

prefixCLock: 'Clock'

sucessClock: 'The time on this world is &e%time%'

## Day

prefixDay: 'Day'

sucessDay: 'The time was set to day.'

## Night

prefixNight: 'Night'

sucessNight: 'The time was set to night.'

## Sun

prefixSun: 'Sun'

sucessSun: 'The weather was set to &eSUNNY&7.'

## Rain

prefixRain: 'Rain'

sucessRain: 'The weather was set to &eRAINY&7.'

## Thunder

prefixThunder: 'Thunder'

sucessThunder: 'The weather was set to &eTHUNDER&7.'

## Smelt

prefixSmelt: 'Smelt'

sucessSmelt: 'The item was smelted sucessfully.'

invalidItemSmelt: 'This item cannot be smelted.'

noItemSmelt: 'You must hold the item on your main hand to smelt it.'