name: OgroEssentials
main: me.luligabi.ogroessentials.OgroEssentials
version: 1.0
author: [Luligabi]
api-version: 1.16
website: https://github.com/Luligabi1/OgroEssentials
commands:
    ogroessentials:
       aliases: [oe]
       description: Exibe informações do Plugin.
    gamemode:
       aliases: [gm]
       description: Mude seu Modo de Jogo.
    heal:
       description: Cure totalmente você ou um alvo.
    feed:
       description: Sacie totalmente a fome de um alvo ou você mesmo.
    tphere:
       description: Teleporte um jogador para a sua localização.
    tpall:
       description: Teleporte todos os jogadores a sua localização.
    clearchat:
       description: Limpe o chat totalmente.      
    clock:
       description: Veja o horário atual no mundo em ticks.       
    day:
       description: Define o horário do mundo atual para dia.
    night:
       description: Define o horário do mundo atual para noite.
    sun:
       description: Define o clima do mundo atual para ensolarado.
    rain:
       description: Define o clima do mundo atual para chuvoso.
    thunder:
       aliases: [storm]
       description: Define o clima do mundo atual para trovejoso.
    smelt:
       description: Derrete minérios de ferro e ouro em barras.